name: gitee sync Morris
on:
  schedule:
    - cron: "0 20 * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/hb0730
          dst: gitee/hb0730
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "boot-admin-ui"
          static_list: "boot-admin-ui"
          force_update: true
